columnas_requeridas_A = [
            'CÓDIGO DE LA INSTITUCIÓN',
            'INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)',
            'SECTOR IES',
            'CARÁCTER IES',
            'DEPARTAMENTO DE DOMICILIO DE LA IES',
            'MUNICIPIO DE DOMICILIO DE LA IES',
            'IES ACREDITADA',
            'CÓDIGO SNIES DEL PROGRAMA',
            'PROGRAMA ACADÉMICO',
            'PROGRAMA ACREDITADO',
            'NIVEL ACADÉMICO',
            'NIVEL DE FORMACIÓN',
            'MODALIDAD',
            'ÁREA DE CONOCIMIENTO',
            'NÚCLEO BÁSICO DEL CONOCIMIENTO (NBC)',
            'DESC CINE CAMPO AMPLIO',
            'DESC CINE CAMPO ESPECIFICO',
            'DESC CINE CAMPO DETALLADO',
            'DEPARTAMENTO DE OFERTA DEL PROGRAMA',
            'MUNICIPIO DE OFERTA DEL PROGRAMA',
            'ID SEXO',
            'AÑO',
            'SEMESTRE',
            'ADMITIDOS'
        ]
columnas_requeridas_G = [
            'CÓDIGO DE LA INSTITUCIÓN',
            'INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)',
            'SECTOR IES',
            'CARÁCTER IES',
            'DEPARTAMENTO DE DOMICILIO DE LA IES',
            'MUNICIPIO DE DOMICILIO DE LA IES',
            'IES ACREDITADA',
            'CÓDIGO SNIES DEL PROGRAMA',
            'PROGRAMA ACADÉMICO',
            'PROGRAMA ACREDITADO',
            'NIVEL ACADÉMICO',
            'NIVEL DE FORMACIÓN',
            'MODALIDAD',
            'ÁREA DE CONOCIMIENTO',
            'NÚCLEO BÁSICO DEL CONOCIMIENTO (NBC)',
            'DESC CINE CAMPO AMPLIO',
            'DESC CINE CAMPO ESPECIFICO',
            'DESC CINE CAMPO DETALLADO',
            'DEPARTAMENTO DE OFERTA DEL PROGRAMA',
            'MUNICIPIO DE OFERTA DEL PROGRAMA',
            'ID SEXO',
            'AÑO',
            'SEMESTRE',
            'GRADUADOS'
        ]
columnas_requeridas_I = [
            'CÓDIGO DE LA INSTITUCIÓN',
            'INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)',
            'SECTOR IES',
            'CARÁCTER IES',
            'DEPARTAMENTO DE DOMICILIO DE LA IES',
            'MUNICIPIO DE DOMICILIO DE LA IES',
            'IES ACREDITADA',
            'CÓDIGO SNIES DEL PROGRAMA',
            'PROGRAMA ACADÉMICO',
            'PROGRAMA ACREDITADO',
            'NIVEL ACADÉMICO',
            'NIVEL DE FORMACIÓN',
            'MODALIDAD',
            'ÁREA DE CONOCIMIENTO',
            'NÚCLEO BÁSICO DEL CONOCIMIENTO (NBC)',
            'DESC CINE CAMPO AMPLIO',
            'DESC CINE CAMPO ESPECIFICO',
            'DESC CINE CAMPO DETALLADO',
            'DEPARTAMENTO DE OFERTA DEL PROGRAMA',
            'MUNICIPIO DE OFERTA DEL PROGRAMA',
            'ID SEXO',
            'AÑO',
            'SEMESTRE',
            'INSCRITOS'
        ]
columnas_requeridas_M = [
            'CÓDIGO DE LA INSTITUCIÓN',
            'INSTITUCIÓN DE EDUCACIÓN SUPERIOR (IES)',
            'SECTOR IES',
            'CARÁCTER IES',
            'DEPARTAMENTO DE DOMICILIO DE LA IES',
            'MUNICIPIO DE DOMICILIO DE LA IES',
            'IES ACREDITADA',
            'CÓDIGO SNIES DEL PROGRAMA',
            'PROGRAMA ACADÉMICO',
            'PROGRAMA ACREDITADO',
            'NIVEL ACADÉMICO',
            'NIVEL DE FORMACIÓN',
            'MODALIDAD',
            'ÁREA DE CONOCIMIENTO',
            'NÚCLEO BÁSICO DEL CONOCIMIENTO (NBC)',
            'DESC CINE CAMPO AMPLIO',
            'DESC CINE CAMPO ESPECIFICO',
            'DESC CINE CAMPO DETALLADO',
            'DEPARTAMENTO DE OFERTA DEL PROGRAMA',
            'MUNICIPIO DE OFERTA DEL PROGRAMA',
            'ID SEXO',
            'AÑO',
            'SEMESTRE',
            'MATRICULADOS'
        ]